##
## Basic way
##
## One docker compose have 2 service
## backend (Spring Boot) and database (MySQL database image)
## Networks it is importance for config database in spring boot
version: '3'

services:

  database: # service name
    container_name: mysql_database # *** define container name
    restart: always # *** set docker-compose.yml to always restart this container if it fails.
    image: mysql:latest # *** same -t , -tag
    environment:
      - MYSQL_DATABASE=to_do_apps_docker
      - MYSQL_USER=ttknp
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=54321 # if MYSQL_PASSWORD didn't set I can access database using root , password
    ports:
      # 3309 outside port to remote to inside 3306
      - '3309:3306'
    volumes: # for storing value on container
      # second way use with your volume for storing data (use volume name instead folder name)
      - information-database:/var/lib/mysql
    networks:  # It's Importance. Create a docker network to communicate Spring boot application and MySQL database
      - springboot-mysql-net


#  backend:
#    container_name: springboot
#    build: .
#    image: springboot
#    ports:
#      - '${SPRINGBOOT_EXPOSED_PORT}:8080'
      # depends_on: dependency order, mysqldb is started before backend ?
      # - database
#    links: # to link containers over a network. When we link containers, Docker creates environment variables and adds containers to the known hosts list
#      - database
#    environment: # environmental variables that Spring Boot application uses
#      - spring.datasource.url=jdbc:mysql://$PMA_HOST_DATABASE:3306/$SQLD_DATABASE?allowPublicKeyRetrieval=true
#    networks:
#      - springboot-mysql-net
#    stdin_open: true # stdin_open and tty: keep open the terminal after building container
#    tty: true


volumes: # for storing value on container
  information-database: # define volume name as information-database
    driver: local # use only current pc


networks: # It's Importance. Create a docker network to communicate Spring boot application and MySQL database
  # Here springboot-mysql-net is the network name.
  springboot-mysql-net:


# Step to run
# case you use default naming of docker compose as docker-compose.yml
# 1. docker-compose up -d --build <service name>
# And you can specify path with -f <path to docker compose>
# 1.1 docker-compose -f dockercomponses/one/docker-compose.yml up -d --build <service name>

# way to access container
# 3. docker exec -it <container id> sh
# ** now you can use command as linux note this case mysql is on /var/lib/mysql/
# 3.1 exit ** for leaving container

# when container created
# all service will be inside container
# as spring-boot-on-docker-app-docker-componse (container  name) have database , app,...