spring.application.name=spring-boot-on-docker-app
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
base-rest-prefix=/api
spring.config.import=classpath:info/configs.properties
# ** connect mysql on docker
# you notice something ?
# when you remote to mysql on docker with any software
# jdbc:mysql://<localhost or 127.0.0.1>:<port access>/<database>
# but when jpa spring boot on docker connect to mysql on docker
# jdbc:mysql://<Wireless LAN adapter Wi-Fi IP4 Address>:<port access>/<database>
spring.datasource.url=${MYSQLD_URL}
spring.datasource.username=${MYSQLD_USERNAME}
spring.datasource.password=${MYSQLD_PASSWORD}
# on config spring jpa on local to docker *** the driver didn't importance
# spring.jpa.database-platform=${MYSQLL_DRIVER}
# on config spring jpa docker *** the driver it's importance
# use "org.hibernate.dialect.MySQLDialect" in hibernate 6
spring.jpa.database-platform=${MYSQLD_DRIVER}
spring.jpa.show-sql=true
