##
## This docker compose file for service's database
##
version: '3'

services:
  database:
    container_name: mysql_database # *** define container name
    restart: always # I ask docker-compose.yml to always restart this container if it fails.
    image: mysql:latest
    ## --env-file flag is about (and only) substitution in compose file
    env_file: # *** import your .env file ** have to no named ?
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQLD_DATABASE}
      - MYSQL_USER=${MYSQLD_USERNAME}
      - MYSQL_PASSWORD=${MYSQLD_PASSWORD}
      - MYSQL_ROOT_PASSWORD=54321 # if MYSQL_PASSWORD didn't set I can access database using root , password
    ports:
      - '${MYSQLD_PORT_REMOTE}:3306'
    volumes: # for storing value on container
      # use volume name instead folder name the name is information-database
      - information-database:/var/lib/mysql
    networks: # It's Importance. Create a docker network to communicate Spring boot application and MySQL database
      # the name is springboot-mysql-net
      - springboot-mysql-net



volumes: # for storing value on container
  information-database: # define volume name as information-database
    driver: local # use only current pc


networks: # It's Importance. Create a docker network to communicate Spring boot application and MySQL database
  # Here springboot-mysql-net is the network name.
  springboot-mysql-net: